version: '3.5'

services:
  app:
    container_name: tidio
    build:
      context: .  
      dockerfile: Dockerfile
    volumes:
      - .:/app

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  db:
    image: postgres:latest
    container_name: postgresql-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tidio
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresql-db
    ports:
      - "5432:5432"
    volumes:
      - .:/app

  amqp:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
