parameters:

services:
    _defaults:
        autowire: true 
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    # Messenger Bus
    _instanceof:
        App\Domain\Messenger\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Domain\Messenger\EventListenerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }
