services:
  _defaults:
    public: true

  App\Domain\Repository\EmployeeRepositoryInterface:
    public: true
    class: 'App\Infrastructure\Repository\EmployeeRepository'
    arguments:
      $registry: '@Doctrine\Persistence\ManagerRegistry'
  App\Domain\Repository\SalaryRepositoryInterface:
    public: true
    class: 'App\Infrastructure\Repository\SalaryRepository'
    arguments:
      $registry: '@Doctrine\Persistence\ManagerRegistry'
  App\Domain\Repository\DepartmentRepositoryInterface:
    public: true
    class: 'App\Infrastructure\Repository\DepartmentRepository'
    arguments:
      $registry: '@Doctrine\Persistence\ManagerRegistry'